SimpleBlog/SimpleBlog/Areas/Admin/Models/PostViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SimpleBlog.Areas.Admin.Models
{
    public class PostViewModel
    {
        public int CategoryId { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string Title { get; set; }
        public SelectList CategoryList { get; set; }
    }
}

SimpleBlog/SimpleBlog/Areas/Admin/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SB.Core.DTO;
using SB.Core.Services;
using SimpleBlog.Areas.Admin.Models;
using SimpleBlog.Datatable;

namespace SimpleBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PostController : Controller
    {
        ICategory category;
        IPost post;
        IMapper mapper;
        public PostController(ICategory _category, IMapper _mapper, IPost _post)
        {
            category = _category;
            mapper = _mapper;
            post = _post;
        }

        public IActionResult Index()
        {
            var categories = category.GetAll();

            var model = new PostViewModel()
            {
                CategoryList = new SelectList(categories, "Id", "Name")
            };

            return View(model);
        }

        public JsonResult Add(PostViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(false);
            }

            var dto = mapper.Map<PostDto>(model);

            return Json(post.Add(dto));
        }


        public JsonResult GetAll(DataTableParameterModel param)
        {
            var data = post.GetAll();

            return Json(
                new
                {
                    draw = param.Draw,
                    recordsTotal = data.Count,
                    recordsFiltered = data.Count,
                    data = data
                });
        }
    }
}

SimpleBlog/SimpleBlog/Pages/Post/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using SimpleBlog.Data;
using SimpleBlog.Data.Entities;

namespace SimpleBlog.Pages.Post
{
    public class CreateModel : PageModel
    {
        private readonly SimpleBlog.Data.ApplicationDbContext _context;

        public CreateModel(SimpleBlog.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public SimpleBlog.Data.Entities.Post Post { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Posts.Add(Post);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

SimpleBlog/SimpleBlog/Pages/Post/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleBlog.Data;
using SimpleBlog.Data.Entities;

namespace SimpleBlog.Pages.Post
{
    public class DeleteModel : PageModel
    {
        private readonly SimpleBlog.Data.ApplicationDbContext _context;

        public DeleteModel(SimpleBlog.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public SimpleBlog.Data.Entities.Post Post { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);

            if (Post == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Post = await _context.Posts.FindAsync(id);

            if (Post != null)
            {
                _context.Posts.Remove(Post);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

SimpleBlog/SimpleBlog/Pages/Post/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleBlog.Data;
using SimpleBlog.Data.Entities;

namespace SimpleBlog.Pages.Post
{
    public class DetailsModel : PageModel
    {
        private readonly SimpleBlog.Data.ApplicationDbContext _context;

        public DetailsModel(SimpleBlog.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public SimpleBlog.Data.Entities.Post Post { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);

            if (Post == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

SimpleBlog/SimpleBlog/Pages/Post/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SimpleBlog.Data;
using SimpleBlog.Data.Entities;

namespace SimpleBlog.Pages.Post
{
    public class EditModel : PageModel
    {
        private readonly SimpleBlog.Data.ApplicationDbContext _context;

        public EditModel(SimpleBlog.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public SimpleBlog.Data.Entities.Post Post { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Post = await _context.Posts.SingleOrDefaultAsync(m => m.Id == id);

            if (Post == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Post).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                
            }

            return RedirectToPage("./Index");
        }
    }
}

SimpleBlog/SimpleBlog/Pages/Post/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using SimpleBlog.Data;
using SimpleBlog.Data.Entities;

namespace SimpleBlog.Pages.Post
{
    public class IndexModel : PageModel
    {
        private readonly SimpleBlog.Data.ApplicationDbContext _context;

        public IndexModel(SimpleBlog.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public IList<SimpleBlog.Data.Entities.Post> Post { get;set; }

        public async Task OnGetAsync()
        {
            Post = await _context.Posts.ToListAsync();
        }
    }
}

SimpleBlog/SimpleBlog/Areas/Admin/Views/Post/Index.cshtml
@model SimpleBlog.Areas.Admin.Models.PostViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2>Posts</h2>
<div class="row">
    <div class="col-lg-12 form-group">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add New</button>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <form id="frmAddPost" asp-controller="Post" asp-action="Add" method="post">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Add New Post</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="col-form-label" asp-for="CategoryId"></label>
                                <select class="form-control" asp-for="CategoryId" asp-items="@Model.CategoryList"></select>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" asp-for="Title"></label>
                                <textarea class="form-control" asp-for="Title"></textarea>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" asp-for="Detail"></label>
                                <textarea class="form-control" asp-for="Detail"></textarea>
                            </div>
                            <div class="form-group">
                                <label class="col-form-label" asp-for="Description"></label>
                                <textarea class="form-control" asp-for="Description"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <table id="example" class="display" style=""></table>
    </div>
</div>


<script>

    $(document).ready(function() {
        $('#example').DataTable( {
            "processing": true,
            "serverSide": true,
            "searching": false,
            "ajax": '@Url.Action("GetAll","Post")',
            columns: [{
                title: "Category Name",
                data: "categoryName"
                },
                {
                    title: "Title",
                    data: "title"
                },
                {
                    title: "Detail",
                    data: "detail"
                },
                {
                    title: "Description",
                    data: "description"
                }
            ]
        });

        // this is the id of the form
        $("#frmAddPost").submit(function (e) {

            $.ajax({
                type: "POST",
                url: '@Url.Action("Add", "Post")',
                data: $("#frmAddPost").serialize(), // serializes the form's elements.
                success: function (data) {
                    if (data) {
                        $('#example').DataTable().ajax.reload();
                    }

                    $('#myModal').modal('hide');
                }
            });
            e.preventDefault();
        });
    } );

</script>