SimpleBlog/SimpleBlog/Areas/Admin/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleBlog.Areas.Admin.Models
{
    public class CategoryViewModel
    {
        public int Id { get; set; }

        [Required]
        [Display(Name="Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name= "Description")]
        public string Description { get; set; }
    }
}

SimpleBlog/SimpleBlog/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SB.Core.DTO;
using SB.Core.Services;
using SimpleBlog.Areas.Admin.Models;
using SimpleBlog.Datatable;
using System.Security.Claims;
using SB.Repository.Entities;
using SB.Service.Identity;

namespace SimpleBlog.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategory _category;
        private readonly IMapper _mapper;
        private readonly SBUserManager _userManager;
        public CategoryController(ICategory category, IMapper mapper, SBUserManager userManager)
        {
            _category = category;
            _mapper = mapper;
            _userManager = userManager;
    }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetAll(DataTableParameterModel param)
        {
            var data = _category.GetAll();
            
            return Json(
                new
                {
                    draw = param.Draw,
                    recordsTotal = data.Count,
                    recordsFiltered = data.Count,
                    data = data
                });
        }

        public JsonResult Add(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(false);
            }

            var dto = _mapper.Map<CategoryDto>(model);
            return Json(_category.Add(dto));
        }

        public JsonResult Edit(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return Json(false);
            }

            var dto = _mapper.Map<CategoryDto>(model);
            return Json(_category.Edit(dto));
        }
    }
}

SimpleBlog/SimpleBlog/Areas/Admin/Views/Category/Index.cshtml
@model SimpleBlog.Areas.Admin.Models.CategoryViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Categories</h2>
<div class="row">
    <div class="col-lg-12 form-group">
        <button id="btnAddNew" type="button" class="btn btn-primary" data-toggle="modal">Add New</button>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <table id="example" class="display" style=""></table>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 border border-primary">
        <form id="frmAddCategory" asp-controller="Category" asp-action="Add" method="post">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-form-label" asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="col-form-label" asp-for="Description"></label>
                    <textarea class="form-control" asp-for="Description"></textarea>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
                    <button class="btn"  type="reset" value="Reset">Reset</button>
                    <button class="btn" onclick='(function () { $("#frmAddCategory").hide(); })();'>Cancel</button>
                </div>
            </div>
        </form>

        <form id="frmEditCategory" asp-controller="Category" asp-action="Edit" method="post">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-form-label" asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" />
                    <input type="hidden" asp-for="Id" />
                </div>
                <div class="form-group">
                    <label class="col-form-label" asp-for="Description"></label>
                    <textarea class="form-control" asp-for="Description"></textarea>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit" value="Submit">Submit</button>
                    <button class="btn" type="reset" value="Reset">Reset</button>
                    <input class="btn" type="button" onclick='(function () { $("#frmEditCategory").hide(); })();' value="Cancel" />
                </div>
            </div>
        </form>
    </div>
</div>


<script>

    $(document).ready(function () {

        $("#frmAddCategory").hide();
        $("#frmEditCategory").hide();

        $('#example').DataTable({
            "select": 'single',
            "processing": true,
            "serverSide": true,
            "searching": false,
            "ajax": '@Url.Action("GetAll","Category")',
            columns: [
                {
                    title: "Name",
                    data: "name"
                },
                {
                    title: "Description",
                    data: "description"
                }
            ]
        });

        // this is the id of the form
        $("#frmAddCategory").submit(function (e) {

            if ($(this).valid()) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Add", "Category")',
                    data: $("#frmAddCategory").serialize(), // serializes the form's elements.
                    success: function (data) {
                        if (data) {
                            $('#example').DataTable().ajax.reload();
                        }

                    }
                });
            }
            e.preventDefault(); // avoid to execute the actual submit of the form.
        });

        $("#frmEditCategory").submit(function (e) {

            if ($(this).valid()) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Edit", "Category")',
                    data: $("#frmEditCategory").serialize(), // serializes the form's elements.
                    success: function (data) {
                        if (data) {
                            $('#example').DataTable().ajax.reload();
                        }

                    }
                });
            }
            e.preventDefault(); // avoid to execute the actual submit of the form.
        });

        $('#btnAddNew').on("click", function () { 

            $("#frmEditCategory").hide();
            $("#frmAddCategory").show();
        });

        var table = $('#example').DataTable();

        table.on('select', function (e, dt, type, indexes) {
            if (type === 'row') {
                var data = table.rows(indexes).data();

                console.log(data);
                oFormObject = document.forms['frmEditCategory'];
                oFormObject.elements["Id"].value = table.rows(indexes).data()[0].id;
                oFormObject.elements["Name"].value = table.rows(indexes).data()[0].name;
                oFormObject.elements["Description"].value = table.rows(indexes).data()[0].description;


                $("#frmAddCategory").hide();
                $("#frmEditCategory").show();
                // do something with the ID of the selected items
            }
        });
    } );

</script>