SimpleBlog/SimpleBlog/ViewComponents/LogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SB.Service.Identity;
namespace SimpleBlog.ViewComponents
{
    public class LogoutViewComponent : ViewComponent
    {
        private readonly SBSignInManager _signInManager;

        public LogoutViewComponent(SBSignInManager signInManager)
        {
            _signInManager = signInManager;
        }

        public IViewComponentResult Invoke()
        {
            var userName = _signInManager.Context.User.Identity.Name;
            return View("Default",userName);
        }
    }
}

SimpleBlog/SimpleBlog/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Simple Blog Admin</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    @*<!-- Bootstrap 3.3.6 -->
        <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
        <!-- Ionicons -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
        <!-- Theme style -->
        <link rel="stylesheet" href="dist/css/AdminLTE.min.css">
        <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
              page. However, you can choose any other skin. Make sure you
              apply the skin class to the body tag so the changes take effect.
        -->
        <link rel="stylesheet" href="dist/css/skins/skin-blue.min.css">*@
    <script src="~/js/thirdParty/jquery-3.1.1.min.js"></script>
    <script src="~/js/thirdParty/jquery-ui-1.12.1.min.js"></script>
    <script src="~/js/thirdParty/jquery.validate.min.js"></script>
    <script src="~/js/thirdParty/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="~/js/thirdParty/font-awesome.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/ionicons.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/custom-bootstrap.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/datatables/dataTables.bootstrap.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/datatables/dataTables.fontAwesome.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/datatables/jquery.dataTables.css">
    @*<link rel="stylesheet" href="https://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css">*@

    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/iCheck/minimal/_all.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/iCheck/square/_all.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/iCheck/flat/_all.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/iCheck/line/_all.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/iCheck/polaris/polaris.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/plugins/iCheck/futurico/futurico.css">
    @*<link rel="stylesheet" href="~/js/thirdParty/stylesheet/tst.min.css">*@
    <link rel="stylesheet" href="~/js/thirdParty/jquerydatetimepicker/jquery.datetimepicker.min.css" />

    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/alt/AdminLTE-bootstrap-social.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/alt/AdminLTE-fullcalendar.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/alt/AdminLTE-select2.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/alt/AdminLTE-select2.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/alt/AdminLTE-without-plugins.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/alt/AdminLTE-without-plugins.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-black.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-black-light.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-blue.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-blue-light.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-green.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-green-light.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-purple.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-purple-light.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-red.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-red-light.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-yellow.min.css">
    <link rel="stylesheet" href="~/js/thirdParty/AdminLTE/dist/css/skins/skin-yellow-light.min.css">


    <link rel="stylesheet" href="~/css/adminsite.css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>SBA</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Simple Blog </b>Admin</span>
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <a class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="container-fluid">
                    <div class="navbar-header" style="padding-left: 10px">
                        <div class="navbar-text navbar-brand-centered">
                            <h3 id="adminTitle"></h3>
                        </div>
                    </div>
                </div>
            </nav>
            @*<nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="~/js/thirdParty/AdminLTE/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs">TST Admin</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header">
                                        <img src="~/js/thirdParty/AdminLTE/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                        <p>
                                            TST Admin
                                            <small>Member since May. 2017</small>
                                        </p>
                                    </li>
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-right">
                                            <a href="#" class="btn btn-default btn-flat">Sign out</a>
                                        </div>
                                    </li>
                                </ul>
                            </li>

                        </ul>
                    </div>
                </nav>*@
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <div class="sidebar-user-panel">
                <vc:logout></vc:logout>
                @*@{ Html.action("GetLoginInfo", "Account");}*@
            </div>
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar Menu -->
                <ul class="sidebar-menu" id="tst-admin-main-navigation">

                    <li class="treeview">
                        <a href="@Url.Action("Index", "Category")"><i class="fa fa-align-justify" aria-hidden="true"></i> <span>Categories</span></a>
                    </li>
                    <li class="treeview">
                        <a href="@Url.Action("Index", "Post")"><i class="fa fa-sitemap" aria-hidden="true"></i> <span>Posts</span></a>
                    </li>

                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div id="tst-admin-main-content" class="content-wrapper container-fluid">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2018 <a>Simple Blog Admin Page</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->

    <script src="~/js/adminLTE.js"></script>
    <script src="~/js/thirdParty/loadingoverlay.min.js"></script>
    <script src="~/js/thirdParty/loadingoverlay_progress.min.js"></script>
    <script src="~/js/thirdParty/underscore.min.js"></script>
    <script src="~/js/thirdParty/jquery.dirtyFields.packed.js"></script>
    <script src="~/js/thirdParty/AdminLTE/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/js/thirdParty/AdminLTE/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/js/thirdParty/AdminLTE/plugins/datatables/dataTables.bootstrap.min.js"></script>
    <script src="~/js/thirdParty/AdminLTE/plugins/fastclick/fastclick.min.js"></script>
    <script src="~/js/thirdParty/AdminLTE/plugins/iCheck/icheck.min.js"></script>
    <script src="~/js/thirdParty/tagsinput/js/typeahead.bundle.js"></script>
    <script src="~/js/thirdParty/ckeditor/ckeditor.js"></script>
    <script src="~/js/thirdParty/jquery.serializejson.js"></script>
    <script src="~/js/thirdParty/AdminLTE/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/thirdParty/AdminLTE/dist/js/app.js"></script>
    <script src="~/js/thirdParty/AdminLTE/dist/js/demo.js"></script>
    <script src="~/js/thirdParty/tagsinput/js/bootstrap-tagsinput.js"></script>
    <script src="~/js/thirdParty/jquerydatetimepicker/jquery.datetimepicker.full.js"></script>
    <script src="~/js/thirdParty/AdminLTE/plugins/datatables/extensions/Select/js/dataTables.select.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.7.0/standard/ckeditor.js"></script>

    <script>

        $(document).ready(function () { 
            $('.modal').on('hidden.bs.modal', function () {
                $(this).find('form')[0].reset();
            });
        })

    </script>
</body>
</html>

SimpleBlog/SimpleBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimpleBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*<environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>*@
    @*<environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>*@
</head>
<body>
    <div class="sitenbt" id="pagenbt">
        <a class="skip-link screen-reader-text" href="https://nordic-btemplates.blogspot.com/#contentnbt">//Skip to content</a>
        <header class="site-headernbt" id="mastheadnbt" role="banner">
            <div class="site-brandingnbt">
                <div class="siteheadersec section" id="siteheadersec">
                    <div class="widget Header" data-version="1" id="Header1">
                        <div id="header-inner">
                            <div class="titlewrapper">
                                <h1 class="site-titlenbt">
                                    <a href="~/">Simple Blog</a>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- .site-branding -->
            <br />
            <nav class="main-navigationnbt" id="site-navigationnbt" role="navigation">
                <button aria-controls="primary-menunbt" aria-expanded="false" class="menu-togglenbt"><i class="fa fa-bars"></i></button>
                <div class="menu-primary-menunbt section" id="menu-primary-menunbt">
                    <div class="widget PageList" data-version="1" id="PageList8">
                        <div class="widget-content">
                            <ul class="menunbt nav-menu" id="primary-menunbt" aria-expanded="false">
                                <li id="currentpage"><a href="~/">Home</a></li>
                                <li><a href="@Url.Action("About","Home")">About</a></li>
                                <li><a href="http://facebook.com/">Facebook</a></li>
                                <li><a href="http://twitter.com/">Twitter</a></li>
                                <li><a href="https://youtube.com/">YouTube</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="search-togglenbt">
                    <i class="fa fa-search"></i>
                    <a class="screen-reader-text" href="https://nordic-btemplates.blogspot.com/#search-containernbt">Search</a>
                </div>
            </nav><!-- #site-navigation -->
            <div class="search-box-wrappernbt clearnbt" id="search-containernbt">
                <div class="search-boxnbt clearnbt">
                    <form action="https://nordic-btemplates.blogspot.com/search/" class="search-formnbt" method="get" role="search">
                        <label>
                            <span class="screen-reader-text">Search for:</span>
                            <input class="search-fieldnbt" name="q" placeholder="Search..." type="search" value="">
                        </label>
                        <input class="search-submitnbt" type="submit" value="Search">
                    </form>
                </div>
            </div>
        </header><!-- #masthead -->
        <div class="site-contentnbt" id="contentnbt">
            <div class="content-areanbt" id="primarynbt">
                @RenderBody()
            </div><!-- #primary -->
        </div><!-- #content -->

        <hr />
        <footer>
            <p style="text-align: center;">&copy; 2018 - SimpleBlog</p>
        </footer>
    </div>

    @*<nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SimpleBlog</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - SimpleBlog</p>
            </footer>
        </div>*@


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*<environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>*@

    @RenderSection("Scripts", required: false)
</body>
</html>